### model
#model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: /n/holylabs/LABS/vlassak_lab/Users/ycchen/LLaMA-Factory/saves/llama3-8b-CodeSteer-gather6-2/full/sft/checkpoint-800

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: CodeSteer_DPO_dataset_total #dpo_en_demo
template: llama3
cutoff_len: 3048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /n/holylabs/LABS/vlassak_lab/Users/ycchen/LLaMA-Factory/saves/llama3-8b-CodeSteer-6-2-dpo/full/dpo
logging_steps: 2
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 500
